//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanji.Interface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hiragana")]
        public global::Kanji.Interface.Models.KanaTypeEnum KunYomiReadingType {
            get {
                return ((global::Kanji.Interface.Models.KanaTypeEnum)(this["KunYomiReadingType"]));
            }
            set {
                this["KunYomiReadingType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hiragana")]
        public global::Kanji.Interface.Models.KanaTypeEnum OnYomiReadingType {
            get {
                return ((global::Kanji.Interface.Models.KanaTypeEnum)(this["OnYomiReadingType"]));
            }
            set {
                this["OnYomiReadingType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hiragana")]
        public global::Kanji.Interface.Models.KanaTypeEnum NanoriReadingType {
            get {
                return ((global::Kanji.Interface.Models.KanaTypeEnum)(this["NanoriReadingType"]));
            }
            set {
                this["NanoriReadingType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int VocabPerPage {
            get {
                return ((int)(this["VocabPerPage"]));
            }
            set {
                this["VocabPerPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int KanjiPerPage {
            get {
                return ((int)(this["KanjiPerPage"]));
            }
            set {
                this["KanjiPerPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string RadicalSetName {
            get {
                return ((string)(this["RadicalSetName"]));
            }
            set {
                this["RadicalSetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frequency")]
        public global::Kanji.Interface.Models.RadicalSortModeEnum RadicalSortMode {
            get {
                return ((global::Kanji.Interface.Models.RadicalSortModeEnum)(this["RadicalSortMode"]));
            }
            set {
                this["RadicalSortMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string SrsLevelSetName {
            get {
                return ((string)(this["SrsLevelSetName"]));
            }
            set {
                this["SrsLevelSetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSrsTagsValue {
            get {
                return ((string)(this["LastSrsTagsValue"]));
            }
            set {
                this["LastSrsTagsValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int SrsEntriesPerPage {
            get {
                return ((int)(this["SrsEntriesPerPage"]));
            }
            set {
                this["SrsEntriesPerPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Home")]
        public global::Kanji.Interface.Models.StartPageEnum StartPage {
            get {
                return ((global::Kanji.Interface.Models.StartPageEnum)(this["StartPage"]));
            }
            set {
                this["StartPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrayShowNotifications {
            get {
                return ((bool)(this["TrayShowNotifications"]));
            }
            set {
                this["TrayShowNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01:00:00")]
        public global::System.TimeSpan TrayCheckInterval {
            get {
                return ((global::System.TimeSpan)(this["TrayCheckInterval"]));
            }
            set {
                this["TrayCheckInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public long TrayNotificationCountThreshold {
            get {
                return ((long)(this["TrayNotificationCountThreshold"]));
            }
            set {
                this["TrayNotificationCountThreshold"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.houhou-srs.com/soft/update.xml")]
        public string UpdateCheckUri {
            get {
                return ((string)(this["UpdateCheckUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastUpdateDate {
            get {
                return ((global::System.DateTime)(this["LastUpdateDate"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24.00:00:00")]
        public global::System.TimeSpan UpdateCheckMinInterval {
            get {
                return ((global::System.TimeSpan)(this["UpdateCheckMinInterval"]));
            }
            set {
                this["UpdateCheckMinInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAutoUpdateCheckEnabled {
            get {
                return ((bool)(this["IsAutoUpdateCheckEnabled"]));
            }
            set {
                this["IsAutoUpdateCheckEnabled"] = value;
            }
        }
    }
}
