//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanji.Interface.Internationalization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kanji.Interface.Internationalization.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured while trying to save the item. If the problem persists, please contact the support..
        /// </summary>
        internal static string SrsItem_EditFailure {
            get {
                return ResourceManager.GetString("SrsItem_EditFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The item must have at least one meaning..
        /// </summary>
        internal static string SrsItem_MeaningsValidationError {
            get {
                return ResourceManager.GetString("SrsItem_MeaningsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The item must have at least one reading..
        /// </summary>
        internal static string SrsItem_ReadingsValidationError {
            get {
                return ResourceManager.GetString("SrsItem_ReadingsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abbreviation.
        /// </summary>
        internal static string VocabCat_Abbreviation {
            get {
                return ResourceManager.GetString("VocabCat_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adjective.
        /// </summary>
        internal static string VocabCat_Adjective {
            get {
                return ResourceManager.GetString("VocabCat_Adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adverb.
        /// </summary>
        internal static string VocabCat_Adverb {
            get {
                return ResourceManager.GetString("VocabCat_Adverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adverbial noun.
        /// </summary>
        internal static string VocabCat_AdverbialNoun {
            get {
                return ResourceManager.GetString("VocabCat_AdverbialNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anatomical term.
        /// </summary>
        internal static string VocabCat_Anatomy {
            get {
                return ResourceManager.GetString("VocabCat_Anatomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archaic verb.
        /// </summary>
        internal static string VocabCat_ArchaicVerb {
            get {
                return ResourceManager.GetString("VocabCat_ArchaicVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archaism.
        /// </summary>
        internal static string VocabCat_Archaism {
            get {
                return ResourceManager.GetString("VocabCat_Archaism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Architecture term.
        /// </summary>
        internal static string VocabCat_Architecture {
            get {
                return ResourceManager.GetString("VocabCat_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Astronomy term.
        /// </summary>
        internal static string VocabCat_Astronomy {
            get {
                return ResourceManager.GetString("VocabCat_Astronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phonetic.
        /// </summary>
        internal static string VocabCat_Ateji {
            get {
                return ResourceManager.GetString("VocabCat_Ateji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auxiliary.
        /// </summary>
        internal static string VocabCat_Auxiliary {
            get {
                return ResourceManager.GetString("VocabCat_Auxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auxiliary adjective.
        /// </summary>
        internal static string VocabCat_AuxiliaryAdjective {
            get {
                return ResourceManager.GetString("VocabCat_AuxiliaryAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auxiliary verb.
        /// </summary>
        internal static string VocabCat_AuxiliaryVerb {
            get {
                return ResourceManager.GetString("VocabCat_AuxiliaryVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baseball term.
        /// </summary>
        internal static string VocabCat_Baseball {
            get {
                return ResourceManager.GetString("VocabCat_Baseball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Biology term.
        /// </summary>
        internal static string VocabCat_Biology {
            get {
                return ResourceManager.GetString("VocabCat_Biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Botany term.
        /// </summary>
        internal static string VocabCat_Botany {
            get {
                return ResourceManager.GetString("VocabCat_Botany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buddhist term.
        /// </summary>
        internal static string VocabCat_BuddhistTerm {
            get {
                return ResourceManager.GetString("VocabCat_BuddhistTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business term.
        /// </summary>
        internal static string VocabCat_Business {
            get {
                return ResourceManager.GetString("VocabCat_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemistry term.
        /// </summary>
        internal static string VocabCat_Chemistry {
            get {
                return ResourceManager.GetString("VocabCat_Chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Children&apos;s language.
        /// </summary>
        internal static string VocabCat_Children {
            get {
                return ResourceManager.GetString("VocabCat_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colloquialism.
        /// </summary>
        internal static string VocabCat_Colloquialism {
            get {
                return ResourceManager.GetString("VocabCat_Colloquialism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Computer term.
        /// </summary>
        internal static string VocabCat_ComputerTerminology {
            get {
                return ResourceManager.GetString("VocabCat_ComputerTerminology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conjunction.
        /// </summary>
        internal static string VocabCat_Conjunction {
            get {
                return ResourceManager.GetString("VocabCat_Conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Counter.
        /// </summary>
        internal static string VocabCat_Counter {
            get {
                return ResourceManager.GetString("VocabCat_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Derogative.
        /// </summary>
        internal static string VocabCat_Derogatory {
            get {
                return ResourceManager.GetString("VocabCat_Derogatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Economics term.
        /// </summary>
        internal static string VocabCat_Economy {
            get {
                return ResourceManager.GetString("VocabCat_Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Engineering term.
        /// </summary>
        internal static string VocabCat_Engineering {
            get {
                return ResourceManager.GetString("VocabCat_Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exclusively kana.
        /// </summary>
        internal static string VocabCat_ExclusivelyKana {
            get {
                return ResourceManager.GetString("VocabCat_ExclusivelyKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exclusively kanji.
        /// </summary>
        internal static string VocabCat_ExclusivelyKanji {
            get {
                return ResourceManager.GetString("VocabCat_ExclusivelyKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expression.
        /// </summary>
        internal static string VocabCat_Expression {
            get {
                return ResourceManager.GetString("VocabCat_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Familiar.
        /// </summary>
        internal static string VocabCat_Familiar {
            get {
                return ResourceManager.GetString("VocabCat_Familiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Female term.
        /// </summary>
        internal static string VocabCat_Female {
            get {
                return ResourceManager.GetString("VocabCat_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finance term.
        /// </summary>
        internal static string VocabCat_Finance {
            get {
                return ResourceManager.GetString("VocabCat_Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Food term.
        /// </summary>
        internal static string VocabCat_Food {
            get {
                return ResourceManager.GetString("VocabCat_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geology term.
        /// </summary>
        internal static string VocabCat_Geology {
            get {
                return ResourceManager.GetString("VocabCat_Geology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geometry term.
        /// </summary>
        internal static string VocabCat_Geometry {
            get {
                return ResourceManager.GetString("VocabCat_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Special reading.
        /// </summary>
        internal static string VocabCat_Gikun {
            get {
                return ResourceManager.GetString("VocabCat_Gikun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerb {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -aru godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbAru {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbAru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -bu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbBu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -gu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbGu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbGu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -iku godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbIku {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbIku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -ku godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbKu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbKu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -mu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbMu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbMu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -nu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbNu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbNu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -ru godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbRu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irr. -ru godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbRuIrregular {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbRuIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -su godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbSu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -tsu godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbTsu {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbTsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -u godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbU {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irr. -u godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbUIrregular {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbUIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -uru godan verb.
        /// </summary>
        internal static string VocabCat_GodanVerbUru {
            get {
                return ResourceManager.GetString("VocabCat_GodanVerbUru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hokkaido-ben.
        /// </summary>
        internal static string VocabCat_HokkaidoBen {
            get {
                return ResourceManager.GetString("VocabCat_HokkaidoBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honorific.
        /// </summary>
        internal static string VocabCat_Honorific {
            get {
                return ResourceManager.GetString("VocabCat_Honorific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Humble.
        /// </summary>
        internal static string VocabCat_Humble {
            get {
                return ResourceManager.GetString("VocabCat_Humble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -i adjective.
        /// </summary>
        internal static string VocabCat_IAdjective {
            get {
                return ResourceManager.GetString("VocabCat_IAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ichidan verb.
        /// </summary>
        internal static string VocabCat_IchidanVerb {
            get {
                return ResourceManager.GetString("VocabCat_IchidanVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -zuru ichidan verb.
        /// </summary>
        internal static string VocabCat_IchidanVerbZuru {
            get {
                return ResourceManager.GetString("VocabCat_IchidanVerbZuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Idiomatic expression.
        /// </summary>
        internal static string VocabCat_Idiomatic {
            get {
                return ResourceManager.GetString("VocabCat_Idiomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interjection.
        /// </summary>
        internal static string VocabCat_Interjection {
            get {
                return ResourceManager.GetString("VocabCat_Interjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intransitive.
        /// </summary>
        internal static string VocabCat_IntransitiveVerb {
            get {
                return ResourceManager.GetString("VocabCat_IntransitiveVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irregular kana usage.
        /// </summary>
        internal static string VocabCat_IrregularKanaUsage {
            get {
                return ResourceManager.GetString("VocabCat_IrregularKanaUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irregular kanji usage.
        /// </summary>
        internal static string VocabCat_IrregularKanjiUsage {
            get {
                return ResourceManager.GetString("VocabCat_IrregularKanjiUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irregular okurigana.
        /// </summary>
        internal static string VocabCat_IrregularOkuriganaUsage {
            get {
                return ResourceManager.GetString("VocabCat_IrregularOkuriganaUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irregular verb.
        /// </summary>
        internal static string VocabCat_IrregularVerb {
            get {
                return ResourceManager.GetString("VocabCat_IrregularVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Humorous term.
        /// </summary>
        internal static string VocabCat_Jocular {
            get {
                return ResourceManager.GetString("VocabCat_Jocular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kansai-ben.
        /// </summary>
        internal static string VocabCat_KansaiBen {
            get {
                return ResourceManager.GetString("VocabCat_KansaiBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kantou-ben.
        /// </summary>
        internal static string VocabCat_KantouBen {
            get {
                return ResourceManager.GetString("VocabCat_KantouBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -kari adjective (arch.).
        /// </summary>
        internal static string VocabCat_KariAdjective {
            get {
                return ResourceManager.GetString("VocabCat_KariAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -ku adjective (arch.).
        /// </summary>
        internal static string VocabCat_KuAdjective {
            get {
                return ResourceManager.GetString("VocabCat_KuAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kuru verb.
        /// </summary>
        internal static string VocabCat_KuruVerb {
            get {
                return ResourceManager.GetString("VocabCat_KuruVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kyoto-ben.
        /// </summary>
        internal static string VocabCat_KyotoBen {
            get {
                return ResourceManager.GetString("VocabCat_KyotoBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kyuushuu-ben.
        /// </summary>
        internal static string VocabCat_KyuushuuBen {
            get {
                return ResourceManager.GetString("VocabCat_KyuushuuBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Law term.
        /// </summary>
        internal static string VocabCat_Law {
            get {
                return ResourceManager.GetString("VocabCat_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linguistics term.
        /// </summary>
        internal static string VocabCat_Linguistics {
            get {
                return ResourceManager.GetString("VocabCat_Linguistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Male term.
        /// </summary>
        internal static string VocabCat_Male {
            get {
                return ResourceManager.GetString("VocabCat_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Male slang.
        /// </summary>
        internal static string VocabCat_MaleSlang {
            get {
                return ResourceManager.GetString("VocabCat_MaleSlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manga slang.
        /// </summary>
        internal static string VocabCat_MangaSlang {
            get {
                return ResourceManager.GetString("VocabCat_MangaSlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Martial arts term.
        /// </summary>
        internal static string VocabCat_MartialArts {
            get {
                return ResourceManager.GetString("VocabCat_MartialArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mathematics term.
        /// </summary>
        internal static string VocabCat_Mathematics {
            get {
                return ResourceManager.GetString("VocabCat_Mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medicine term.
        /// </summary>
        internal static string VocabCat_Medicine {
            get {
                return ResourceManager.GetString("VocabCat_Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Military term.
        /// </summary>
        internal static string VocabCat_Military {
            get {
                return ResourceManager.GetString("VocabCat_Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music term.
        /// </summary>
        internal static string VocabCat_Music {
            get {
                return ResourceManager.GetString("VocabCat_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -na adjective.
        /// </summary>
        internal static string VocabCat_NaAdjective {
            get {
                return ResourceManager.GetString("VocabCat_NaAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nagano-ben.
        /// </summary>
        internal static string VocabCat_NaganoBen {
            get {
                return ResourceManager.GetString("VocabCat_NaganoBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -nari adjective (arch.).
        /// </summary>
        internal static string VocabCat_NariAdjective {
            get {
                return ResourceManager.GetString("VocabCat_NariAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -u nidan verb.
        /// </summary>
        internal static string VocabCat_NidanVerbU {
            get {
                return ResourceManager.GetString("VocabCat_NidanVerbU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no-adjective noun.
        /// </summary>
        internal static string VocabCat_NoAdjective {
            get {
                return ResourceManager.GetString("VocabCat_NoAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Noun.
        /// </summary>
        internal static string VocabCat_Noun {
            get {
                return ResourceManager.GetString("VocabCat_Noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric.
        /// </summary>
        internal static string VocabCat_Numeric {
            get {
                return ResourceManager.GetString("VocabCat_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irr. nu verb.
        /// </summary>
        internal static string VocabCat_NuVerb {
            get {
                return ResourceManager.GetString("VocabCat_NuVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obscure term.
        /// </summary>
        internal static string VocabCat_Obscure {
            get {
                return ResourceManager.GetString("VocabCat_Obscure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obsolete.
        /// </summary>
        internal static string VocabCat_Obsolete {
            get {
                return ResourceManager.GetString("VocabCat_Obsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irregular kana.
        /// </summary>
        internal static string VocabCat_OldOrIrregularKana {
            get {
                return ResourceManager.GetString("VocabCat_OldOrIrregularKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Onomatopoeia.
        /// </summary>
        internal static string VocabCat_Onomatopoeic {
            get {
                return ResourceManager.GetString("VocabCat_Onomatopoeic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Osaka-ben.
        /// </summary>
        internal static string VocabCat_OsakaBen {
            get {
                return ResourceManager.GetString("VocabCat_OsakaBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outdated kana usage.
        /// </summary>
        internal static string VocabCat_OutdatedKana {
            get {
                return ResourceManager.GetString("VocabCat_OutdatedKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outdated kanji usage.
        /// </summary>
        internal static string VocabCat_OutdatedKanji {
            get {
                return ResourceManager.GetString("VocabCat_OutdatedKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Particle.
        /// </summary>
        internal static string VocabCat_Particle {
            get {
                return ResourceManager.GetString("VocabCat_Particle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Physics term.
        /// </summary>
        internal static string VocabCat_Physics {
            get {
                return ResourceManager.GetString("VocabCat_Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poetical term.
        /// </summary>
        internal static string VocabCat_Poetical {
            get {
                return ResourceManager.GetString("VocabCat_Poetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polite.
        /// </summary>
        internal static string VocabCat_Polite {
            get {
                return ResourceManager.GetString("VocabCat_Polite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefix.
        /// </summary>
        internal static string VocabCat_Prefix {
            get {
                return ResourceManager.GetString("VocabCat_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefix noun.
        /// </summary>
        internal static string VocabCat_PrefixNoun {
            get {
                return ResourceManager.GetString("VocabCat_PrefixNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prenominal adjective.
        /// </summary>
        internal static string VocabCat_PrenominalAdjective {
            get {
                return ResourceManager.GetString("VocabCat_PrenominalAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prenominal.
        /// </summary>
        internal static string VocabCat_PrenominalNounVerb {
            get {
                return ResourceManager.GetString("VocabCat_PrenominalNounVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pronoun.
        /// </summary>
        internal static string VocabCat_Pronoun {
            get {
                return ResourceManager.GetString("VocabCat_Pronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proper noun.
        /// </summary>
        internal static string VocabCat_ProperNoun {
            get {
                return ResourceManager.GetString("VocabCat_ProperNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proverb.
        /// </summary>
        internal static string VocabCat_Proverb {
            get {
                return ResourceManager.GetString("VocabCat_Proverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rare.
        /// </summary>
        internal static string VocabCat_Rare {
            get {
                return ResourceManager.GetString("VocabCat_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irr. ru verb (plain form ends with -ri).
        /// </summary>
        internal static string VocabCat_RuVerb {
            get {
                return ResourceManager.GetString("VocabCat_RuVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ryuukyuu-ben.
        /// </summary>
        internal static string VocabCat_RyuukyuuBen {
            get {
                return ResourceManager.GetString("VocabCat_RyuukyuuBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sensitive.
        /// </summary>
        internal static string VocabCat_Sensitive {
            get {
                return ResourceManager.GetString("VocabCat_Sensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -shiku adjective (arch.).
        /// </summary>
        internal static string VocabCat_ShikuAdjective {
            get {
                return ResourceManager.GetString("VocabCat_ShikuAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shinto term.
        /// </summary>
        internal static string VocabCat_Shinto {
            get {
                return ResourceManager.GetString("VocabCat_Shinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slang.
        /// </summary>
        internal static string VocabCat_Slang {
            get {
                return ResourceManager.GetString("VocabCat_Slang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sports term.
        /// </summary>
        internal static string VocabCat_Sports {
            get {
                return ResourceManager.GetString("VocabCat_Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suffix.
        /// </summary>
        internal static string VocabCat_Suffix {
            get {
                return ResourceManager.GetString("VocabCat_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suffix noun.
        /// </summary>
        internal static string VocabCat_SuffixNoun {
            get {
                return ResourceManager.GetString("VocabCat_SuffixNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sumo term.
        /// </summary>
        internal static string VocabCat_Sumo {
            get {
                return ResourceManager.GetString("VocabCat_Sumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -suru verb.
        /// </summary>
        internal static string VocabCat_SuruVerb {
            get {
                return ResourceManager.GetString("VocabCat_SuruVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Irr. -suru verb.
        /// </summary>
        internal static string VocabCat_SuruVerbIrregular {
            get {
                return ResourceManager.GetString("VocabCat_SuruVerbIrregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -suru verb.
        /// </summary>
        internal static string VocabCat_SuruVerbNoun {
            get {
                return ResourceManager.GetString("VocabCat_SuruVerbNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -su verb.
        /// </summary>
        internal static string VocabCat_SuVerb {
            get {
                return ResourceManager.GetString("VocabCat_SuVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -taru adjective.
        /// </summary>
        internal static string VocabCat_TaruAdjective {
            get {
                return ResourceManager.GetString("VocabCat_TaruAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temporal noun.
        /// </summary>
        internal static string VocabCat_TemporalNoun {
            get {
                return ResourceManager.GetString("VocabCat_TemporalNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -to adverb.
        /// </summary>
        internal static string VocabCat_ToAdverb {
            get {
                return ResourceManager.GetString("VocabCat_ToAdverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tosa-ben.
        /// </summary>
        internal static string VocabCat_TosaBen {
            get {
                return ResourceManager.GetString("VocabCat_TosaBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Touhoku-ben.
        /// </summary>
        internal static string VocabCat_TouhokuBen {
            get {
                return ResourceManager.GetString("VocabCat_TouhokuBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transitive.
        /// </summary>
        internal static string VocabCat_TransitiveVerb {
            get {
                return ResourceManager.GetString("VocabCat_TransitiveVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tsugaru-ben.
        /// </summary>
        internal static string VocabCat_TsugaruBen {
            get {
                return ResourceManager.GetString("VocabCat_TsugaruBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usually written in kana.
        /// </summary>
        internal static string VocabCat_UsuallyKana {
            get {
                return ResourceManager.GetString("VocabCat_UsuallyKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usually written in kanji.
        /// </summary>
        internal static string VocabCat_UsuallyKanji {
            get {
                return ResourceManager.GetString("VocabCat_UsuallyKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verb.
        /// </summary>
        internal static string VocabCat_Verb {
            get {
                return ResourceManager.GetString("VocabCat_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vulgar.
        /// </summary>
        internal static string VocabCat_Vulgar {
            get {
                return ResourceManager.GetString("VocabCat_Vulgar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X-rated term.
        /// </summary>
        internal static string VocabCat_X {
            get {
                return ResourceManager.GetString("VocabCat_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -fu yodan verb.
        /// </summary>
        internal static string VocabCat_YodanVerbFu {
            get {
                return ResourceManager.GetString("VocabCat_YodanVerbFu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -ru yodan verb.
        /// </summary>
        internal static string VocabCat_YodanVerbRu {
            get {
                return ResourceManager.GetString("VocabCat_YodanVerbRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoology term.
        /// </summary>
        internal static string VocabCat_Zoology {
            get {
                return ResourceManager.GetString("VocabCat_Zoology", resourceCulture);
            }
        }
    }
}
